// v3.8.awu — BOLTemplate removed. It was a SECOND renderer for the bill of
// lading: a client-side HTML re-render with its own print pipeline, reachable
// from the carrier portal, while the authoritative BOL is generated by
// pdfService and served from /pdf/bol-load/:loadId.
//
// Two renderers for one legal instrument is the Load.rate defect in document
// form — nobody knows which is authoritative until the numbers disagree in front
// of a shipper. The same class was retired for the Rate Confirmation in §13.3
// Item 249.5; that twin was dead, this one was live, which made it worse.
//
// It also held the last hardcoded whaider@ on a carrier-facing document
// (the v3.8.akg authority centralization migrated this file's MC#/DOT# and
// scoped the email out), non-canonical navy #0F1A22 and gold #C9A24D, no
// Playfair at all, and a banner reading "Preview reflects pre-v2.9 design."
//
// Removed only AFTER the carrier could reach the real PDF: /pdf/bol-load/:loadId
// now admits CARRIER behind a per-record ownership check. Order mattered —
// deleting first would have left carriers with no bill of lading at all.
export { InvoiceTemplate } from "./InvoiceTemplate";
export type { InvoiceData, InvoiceLineItem } from "./InvoiceTemplate";
