import { prisma } from "../config/database";
import { checkContractRate } from "./contractRateService";
import { buildLaneContext } from "./aiLearningLoop/contextEngine";

/**
 * AI Auto-Quote Service — Instant Rate Quotes for Shipper RFQs
 *
 * Generates instant rate quotes using market data + historical lane pricing.
 * No human needed for standard lanes. Combines historical load data with
 * base rate calculations, seasonal adjustments, and SRL margin markup.
 *
 * KEY FEATURES:
 * - Historical lane pricing from last 90 days
 * - Equipment-specific base rates with fuel surcharges
 * - Hazmat, temp-controlled, weight, season, distance adjustments
 * - Confidence scoring based on historical data volume
 * - 24-hour quote validity with unique tracking IDs
 */

// ─── Interfaces ─────────────────────────────────────────────────────

export interface QuoteRequest {
  originCity: string;
  originState: string;
  destCity: string;
  destState: string;
  equipmentType: string;
  weight?: number;
  pickupDate?: string;
  commodity?: string;
  isHazmat?: boolean;
  isTempControlled?: boolean;
  customerId?: string;
}

export interface QuoteResponse {
  quotedRate: number;
  ratePerMile: number;
  estimatedMiles: number;
  confidence: "HIGH" | "MEDIUM" | "LOW";
  marketRate: { low: number; avg: number; high: number } | null;
  margin: number;
  breakdown: {
    linehaul: number;
    fuelSurcharge: number;
    accessorials: number;
    total: number;
  };
  validUntil: string;
  quoteId: string;
  autoGenerated: boolean;
  factors: string[];
}

// ─── Constants ──────────────────────────────────────────────────────

const SRL_MARGIN = 0.15; // 15% markup on carrier rate
const FUEL_SURCHARGE_PER_MILE = 0.45;
const QUOTE_VALIDITY_HOURS = 24;

/** Base carrier rates per mile by equipment type */
const BASE_RATES: Record<string, number> = {
  DRY_VAN: 2.50,
  REEFER: 3.10,
  FLATBED: 3.25,
  STEP_DECK: 3.50,
};

/**
 * State-to-state distance lookup (miles) for top 20 US lane pairs.
 * Key format: "XX-YY" where XX < YY alphabetically for consistency.
 */
const STATE_PAIR_DISTANCES: Record<string, number> = {
  "CA-TX": 1400,
  "CA-WA": 800,
  "FL-GA": 350,
  "FL-TX": 1100,
  "GA-NC": 400,
  "GA-TX": 800,
  "IL-IN": 180,
  "IL-MI": 280,
  "IL-OH": 350,
  "IL-TX": 1050,
  "IL-WI": 180,
  "CA-IL": 2000,
  "CA-NY": 2800,
  "FL-NY": 1100,
  "GA-IL": 700,
  "MI-OH": 200,
  "NC-VA": 200,
  "NJ-NY": 80,
  "NJ-PA": 90,
  "NY-PA": 200,
  "OH-PA": 300,
  "PA-VA": 350,
  "TX-OK": 250,
  "CA-AZ": 380,
  "AZ-TX": 1000,
  "CO-TX": 900,
  "MO-TX": 700,
  "IN-OH": 180,
  "TN-TX": 800,
  "AL-GA": 160,
};

/** Approximate state centroid coordinates for straight-line fallback */
const STATE_CENTROIDS: Record<string, { lat: number; lng: number }> = {
  AL: { lat: 32.8, lng: -86.8 },
  AK: { lat: 64.0, lng: -153.0 },
  AZ: { lat: 34.3, lng: -111.7 },
  AR: { lat: 34.8, lng: -92.2 },
  CA: { lat: 36.8, lng: -119.4 },
  CO: { lat: 39.0, lng: -105.5 },
  CT: { lat: 41.6, lng: -72.7 },
  DE: { lat: 39.0, lng: -75.5 },
  FL: { lat: 28.6, lng: -82.4 },
  GA: { lat: 32.7, lng: -83.5 },
  HI: { lat: 20.5, lng: -156.3 },
  ID: { lat: 44.1, lng: -114.7 },
  IL: { lat: 40.0, lng: -89.2 },
  IN: { lat: 39.8, lng: -86.3 },
  IA: { lat: 42.0, lng: -93.5 },
  KS: { lat: 38.5, lng: -98.3 },
  KY: { lat: 37.8, lng: -85.3 },
  LA: { lat: 31.0, lng: -91.9 },
  ME: { lat: 45.3, lng: -69.3 },
  MD: { lat: 39.0, lng: -76.7 },
  MA: { lat: 42.3, lng: -71.8 },
  MI: { lat: 44.3, lng: -84.5 },
  MN: { lat: 46.3, lng: -94.3 },
  MS: { lat: 32.6, lng: -89.7 },
  MO: { lat: 38.4, lng: -92.5 },
  MT: { lat: 47.0, lng: -109.6 },
  NE: { lat: 41.5, lng: -99.8 },
  NV: { lat: 39.3, lng: -116.6 },
  NH: { lat: 43.7, lng: -71.6 },
  NJ: { lat: 40.2, lng: -74.7 },
  NM: { lat: 34.5, lng: -106.0 },
  NY: { lat: 42.2, lng: -74.9 },
  NC: { lat: 35.5, lng: -79.4 },
  ND: { lat: 47.5, lng: -100.5 },
  OH: { lat: 40.4, lng: -82.8 },
  OK: { lat: 35.6, lng: -97.5 },
  OR: { lat: 44.1, lng: -120.5 },
  PA: { lat: 40.9, lng: -77.8 },
  RI: { lat: 41.7, lng: -71.5 },
  SC: { lat: 33.9, lng: -80.9 },
  SD: { lat: 44.4, lng: -100.2 },
  TN: { lat: 35.9, lng: -86.4 },
  TX: { lat: 31.5, lng: -99.3 },
  UT: { lat: 39.3, lng: -111.7 },
  VT: { lat: 44.1, lng: -72.6 },
  VA: { lat: 37.5, lng: -78.9 },
  WA: { lat: 47.4, lng: -120.5 },
  WV: { lat: 38.6, lng: -80.6 },
  WI: { lat: 44.4, lng: -89.8 },
  WY: { lat: 43.0, lng: -107.6 },
};

// ─── Distance Estimation ────────────────────────────────────────────

function getStatePairKey(stateA: string, stateB: string): string {
  const a = stateA.toUpperCase();
  const b = stateB.toUpperCase();
  return a < b ? `${a}-${b}` : `${b}-${a}`;
}

/**
 * Haversine formula for straight-line distance between two lat/lng points.
 * Returns miles. We apply a 1.3x road factor to approximate driving distance.
 */
function haversineDistance(
  lat1: number, lng1: number,
  lat2: number, lng2: number,
): number {
  const R = 3959; // Earth radius in miles
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLng / 2) * Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

function estimateDistance(originState: string, destState: string): number {
  const origin = originState.toUpperCase();
  const dest = destState.toUpperCase();

  if (origin === dest) {
    return 250; // Intra-state default
  }

  // Check lookup table
  const key = getStatePairKey(origin, dest);
  if (STATE_PAIR_DISTANCES[key]) {
    return STATE_PAIR_DISTANCES[key];
  }

  // Fallback: straight-line with road factor
  const originCoord = STATE_CENTROIDS[origin];
  const destCoord = STATE_CENTROIDS[dest];
  if (originCoord && destCoord) {
    const straightLine = haversineDistance(
      originCoord.lat, originCoord.lng,
      destCoord.lat, destCoord.lng,
    );
    return Math.round(straightLine * 1.3); // 1.3x road factor
  }

  return 500; // Ultimate fallback
}

// ─── Market Benchmark ───────────────────────────────────────────────

export async function getMarketBenchmark(
  originState: string,
  destState: string,
  equipmentType: string,
): Promise<{ low: number; avg: number; high: number; count: number } | null> {
  const ninetyDaysAgo = new Date();
  ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90);

  const loads = await prisma.load.findMany({
    where: {
      originState: originState.toUpperCase(),
      destState: destState.toUpperCase(),
      equipmentType,
      pickupDate: { gte: ninetyDaysAgo },
      status: { in: ["DELIVERED", "COMPLETED", "IN_TRANSIT", "AT_PICKUP", "AT_DELIVERY"] },
    },
    select: {
      rate: true,
      distance: true,
    },
  });

  if (loads.length === 0) return null;

  const rates = loads.map((l) => l.rate).sort((a, b) => a - b);
  const sum = rates.reduce((acc, r) => acc + r, 0);
  const avg = sum / rates.length;
  const low = rates[Math.floor(rates.length * 0.1)] ?? rates[0];
  const high = rates[Math.floor(rates.length * 0.9)] ?? rates[rates.length - 1];

  return {
    low: Math.round(low * 100) / 100,
    avg: Math.round(avg * 100) / 100,
    high: Math.round(high * 100) / 100,
    count: loads.length,
  };
}

// ─── Main Quote Engine ──────────────────────────────────────────────

export async function generateQuote(params: QuoteRequest): Promise<QuoteResponse> {
  const {
    originState,
    destState,
    equipmentType,
    weight,
    pickupDate,
    isHazmat = false,
    isTempControlled = false,
    customerId,
  } = params;

  const factors: string[] = [];
  const normalizedEquip = equipmentType.toUpperCase().replace(/[\s-]/g, "_");

  // Check for contract rate first — takes priority over spot pricing
  if (customerId) {
    const contractRate = await checkContractRate(originState, destState, normalizedEquip, customerId);
    if (contractRate) {
      const estimatedMiles = estimateDistance(originState, destState);
      const ratePerMile = contractRate.rate;
      const linehaul = contractRate.flatRate
        ? contractRate.flatRate
        : Math.round(ratePerMile * estimatedMiles * 100) / 100;
      const fuelSurcharge = Math.round(contractRate.fuelSurcharge * estimatedMiles * 100) / 100;
      const total = Math.round((linehaul + fuelSurcharge) * 100) / 100;
      const totalRatePerMile = Math.round((total / estimatedMiles) * 100) / 100;

      const timestamp = Date.now();
      const random4 = Math.random().toString(36).substring(2, 6).toUpperCase();
      const quoteId = `QT-CTR-${timestamp}-${random4}`;
      const validUntil = new Date();
      validUntil.setHours(validUntil.getHours() + QUOTE_VALIDITY_HOURS);

      return {
        quotedRate: total,
        ratePerMile: totalRatePerMile,
        estimatedMiles,
        confidence: "HIGH" as const,
        marketRate: null,
        margin: 0, // Contract rate already includes margin
        breakdown: {
          linehaul,
          fuelSurcharge,
          accessorials: 0,
          total,
        },
        validUntil: validUntil.toISOString(),
        quoteId,
        autoGenerated: true,
        factors: [
          `Contract rate applied for ${contractRate.customer.name}`,
          `Rate: $${ratePerMile.toFixed(2)}/mile${contractRate.flatRate ? ` (flat: $${contractRate.flatRate})` : ""}`,
          `Fuel surcharge: $${contractRate.fuelSurcharge.toFixed(2)}/mile`,
          `Contract valid until ${contractRate.expirationDate.toISOString().slice(0, 10)}`,
        ],
      };
    }
  }

  // 0. Try to get AI-enriched lane context (optional — failures are non-blocking)
  let laneContext: Awaited<ReturnType<typeof buildLaneContext>> | null = null;
  try {
    laneContext = await buildLaneContext(originState, destState);
  } catch {
    /* context enrichment is optional */
  }

  // 1. Estimate distance
  const estimatedMiles = estimateDistance(originState, destState);
  factors.push(`Estimated distance: ${estimatedMiles} miles (${originState.toUpperCase()} → ${destState.toUpperCase()})`);

  // 2. Get historical market data
  const market = await getMarketBenchmark(originState, destState, normalizedEquip);
  let historicalCount = 0;

  // 3. Determine base carrier rate per mile
  let carrierRatePerMile: number;

  if (market && market.count >= 3) {
    // Use historical data — derive rate per mile from average
    const avgHistoricalMiles = estimatedMiles; // Use our estimate since DB may have nulls
    carrierRatePerMile = market.avg / avgHistoricalMiles;
    historicalCount = market.count;
    factors.push(`Historical data: ${market.count} loads on this lane (last 90 days)`);
    factors.push(`Historical avg rate: $${market.avg.toFixed(2)} ($${carrierRatePerMile.toFixed(2)}/mile)`);
  } else if (laneContext?.avgRate) {
    // Use AI context engine lane intelligence as fallback before base rates
    carrierRatePerMile = laneContext.avgRate / estimatedMiles;
    factors.push(`AI lane intelligence avg rate: $${laneContext.avgRate.toFixed(2)} ($${carrierRatePerMile.toFixed(2)}/mile)`);
    if (laneContext.trend) {
      factors.push(`Lane trend: ${laneContext.trend}`);
    }
  } else {
    // Use base rates
    carrierRatePerMile = BASE_RATES[normalizedEquip] || BASE_RATES.DRY_VAN;
    factors.push(`No significant historical data — using base rate: $${carrierRatePerMile.toFixed(2)}/mile for ${normalizedEquip}`);
    if (market && market.count > 0) {
      historicalCount = market.count;
      factors.push(`Limited historical data: ${market.count} load(s) found`);
    }
  }

  // Enrich with AI context signals if available
  if (laneContext) {
    if (laneContext.seasonalFactor && laneContext.seasonalFactor !== 1.0) {
      factors.push(`AI seasonal factor: ${laneContext.seasonalFactor.toFixed(2)}`);
    }
    if (laneContext.recentAnomalies > 0) {
      factors.push(`AI anomaly alert: ${laneContext.recentAnomalies} recent anomaly(ies) on this lane`);
    }
  }

  // 4. Apply adjustments
  let adjustmentMultiplier = 1.0;

  // Hazmat adjustment
  if (isHazmat) {
    adjustmentMultiplier *= 1.15;
    factors.push("Hazmat surcharge: +15%");
  }

  // Temperature controlled
  if (isTempControlled) {
    adjustmentMultiplier *= 1.10;
    factors.push("Temperature controlled surcharge: +10%");
  }

  // Weight adjustment
  if (weight && weight > 40000) {
    adjustmentMultiplier *= 1.05;
    factors.push(`Heavyweight surcharge (${weight.toLocaleString()} lbs): +5%`);
  }

  // Seasonal adjustment
  const evalDate = pickupDate ? new Date(pickupDate) : new Date();
  const month = evalDate.getMonth() + 1; // 1-12
  if ((month >= 6 && month <= 9) || (month >= 11 && month <= 12)) {
    adjustmentMultiplier *= 1.08;
    const seasonName = month >= 11 ? "holiday" : "summer";
    factors.push(`Peak season (${seasonName}) surcharge: +8%`);
  }

  // Short haul adjustment
  if (estimatedMiles < 200) {
    adjustmentMultiplier *= 1.20;
    factors.push(`Short haul adjustment (${estimatedMiles} miles < 200): +20%/mile`);
  }

  // Long haul discount
  if (estimatedMiles > 1500) {
    adjustmentMultiplier *= 0.95;
    factors.push(`Long haul discount (${estimatedMiles} miles > 1500): -5%/mile`);
  }

  // 5. Calculate final rates
  const adjustedCarrierRatePerMile = carrierRatePerMile * adjustmentMultiplier;
  const linehaul = Math.round(adjustedCarrierRatePerMile * estimatedMiles * 100) / 100;
  const fuelSurcharge = Math.round(FUEL_SURCHARGE_PER_MILE * estimatedMiles * 100) / 100;

  // Accessorials: hazmat flat fee + temp monitoring
  let accessorials = 0;
  if (isHazmat) accessorials += 150;
  if (isTempControlled) accessorials += 100;

  const carrierTotal = linehaul + fuelSurcharge + accessorials;

  // Apply SRL margin
  const marginAmount = Math.round(carrierTotal * SRL_MARGIN * 100) / 100;
  const total = Math.round((carrierTotal + marginAmount) * 100) / 100;
  const ratePerMile = Math.round((total / estimatedMiles) * 100) / 100;

  factors.push(`SRL margin: ${(SRL_MARGIN * 100).toFixed(0)}% ($${marginAmount.toFixed(2)})`);

  // 6. Confidence scoring
  let confidence: "HIGH" | "MEDIUM" | "LOW";
  if (historicalCount >= 10) {
    confidence = "HIGH";
  } else if (historicalCount >= 3) {
    confidence = "MEDIUM";
  } else {
    confidence = "LOW";
  }

  // 7. Generate quote ID and validity
  const timestamp = Date.now();
  const random4 = Math.random().toString(36).substring(2, 6).toUpperCase();
  const quoteId = `QT-${timestamp}-${random4}`;

  const validUntil = new Date();
  validUntil.setHours(validUntil.getHours() + QUOTE_VALIDITY_HOURS);

  // 8. Market rate for response (as customer-facing rates with margin)
  let marketRate: { low: number; avg: number; high: number } | null = null;
  if (market) {
    marketRate = {
      low: Math.round(market.low * (1 + SRL_MARGIN) * 100) / 100,
      avg: Math.round(market.avg * (1 + SRL_MARGIN) * 100) / 100,
      high: Math.round(market.high * (1 + SRL_MARGIN) * 100) / 100,
    };
  }

  return {
    quotedRate: total,
    ratePerMile,
    estimatedMiles,
    confidence,
    marketRate,
    margin: SRL_MARGIN * 100,
    breakdown: {
      linehaul: Math.round((linehaul * (1 + SRL_MARGIN)) * 100) / 100,
      fuelSurcharge: Math.round((fuelSurcharge * (1 + SRL_MARGIN)) * 100) / 100,
      accessorials: Math.round((accessorials * (1 + SRL_MARGIN)) * 100) / 100,
      total,
    },
    validUntil: validUntil.toISOString(),
    quoteId,
    autoGenerated: true,
    factors,
  };
}
