/**
 * Compass PDF Report Generator
 * Generates a professional PDF summary of all Compass carrier compliance checks.
 */

import PDFDocument from "pdfkit";
import * as path from "path";
import * as fs from "fs";
import type { CarrierVettingReport, VettingCheck, CheckResult } from "./carrierVettingService";

type PDFDoc = InstanceType<typeof PDFDocument>;

const COMPANY = {
  name: "Silk Route Logistics Inc.",
  address: "4000 S Westnedge Ave",
  cityStateZip: "Kalamazoo, MI 49008",
  mc: "MC# 01794414",
  dot: "DOT# 4526880",
};

const LOGO_PATH = path.resolve(__dirname, "../../assets/logo.png");
const hasLogo = fs.existsSync(LOGO_PATH);

// Colors
const COLOR = {
  pass: "#16a34a",
  warning: "#d97706",
  fail: "#dc2626",
  navy: "#0d1b2a",
  gold: "#c9a84c",
  lightGray: "#e5e7eb",
  medGray: "#888888",
  darkText: "#1e1e2f",
};

const SYMBOL: Record<CheckResult, string> = {
  PASS: "\u2713",    // check mark
  WARNING: "\u26A0", // warning triangle
  FAIL: "\u2717",    // x mark
};

const RESULT_COLOR: Record<CheckResult, string> = {
  PASS: COLOR.pass,
  WARNING: COLOR.warning,
  FAIL: COLOR.fail,
};

// Category grouping for the 35 checks
interface CheckCategory {
  name: string;
  indices: number[]; // 1-based check numbers
}

const CATEGORIES: CheckCategory[] = [
  { name: "FMCSA Authority & Safety", indices: [1, 2, 3, 4, 5, 6, 7] },
  { name: "Insurance & Financial", indices: [3, 8, 17, 21] },
  { name: "Identity & Fraud", indices: [11, 12, 13, 14, 15, 19, 23, 30, 31] },
  { name: "Compliance & Documentation", indices: [16, 20, 24, 26, 29, 32, 33, 34, 35] },
  { name: "Performance & Operations", indices: [9, 10, 18, 25, 27, 28] },
];

export interface CompassCarrierData {
  companyName: string;
  dotNumber: string;
  mcNumber: string;
  contactName: string;
  tier: string;
  milestone: string;
}

function addHeader(doc: PDFDoc) {
  if (hasLogo) {
    doc.image(LOGO_PATH, 50, 35, { width: 55 });
  }

  doc.fontSize(12).fillColor(COLOR.navy).font("Helvetica-Bold");
  doc.text("SILK ROUTE LOGISTICS INC.", 120, 40);
  doc.fontSize(9).fillColor(COLOR.gold).font("Helvetica");
  doc.text("COMPASS CARRIER COMPLIANCE REPORT", 120, 56);

  // Company info right
  doc.fontSize(7).fillColor(COLOR.medGray).font("Helvetica");
  doc.text(COMPANY.address, 400, 40, { align: "right" });
  doc.text(COMPANY.cityStateZip, 400, 50, { align: "right" });
  doc.text(`${COMPANY.mc} | ${COMPANY.dot}`, 400, 60, { align: "right" });

  doc.moveTo(50, 78).lineTo(560, 78).strokeColor(COLOR.gold).lineWidth(2).stroke();
}

function addFooter(doc: PDFDoc) {
  const y = doc.page.height - 55;
  doc.moveTo(50, y).lineTo(560, y).strokeColor(COLOR.lightGray).lineWidth(0.5).stroke();
  doc.fontSize(6.5).fillColor(COLOR.medGray).font("Helvetica");
  doc.text(
    "This report was generated by the Compass Carrier Compliance Engine.",
    50, y + 6, { align: "center", width: 510 }
  );
  doc.text(
    `${COMPANY.name}, ${COMPANY.cityStateZip}. ${COMPANY.mc} | ${COMPANY.dot}`,
    50, y + 16, { align: "center", width: 510 }
  );
}

function drawSeparator(doc: PDFDoc, y: number) {
  doc.moveTo(50, y).lineTo(560, y).strokeColor(COLOR.gold).lineWidth(1).stroke();
}

function ensureSpace(doc: PDFDoc, needed: number): number {
  const y = (doc as any).y as number;
  if (y + needed > doc.page.height - 70) {
    doc.addPage();
    addHeader(doc);
    addFooter(doc);
    return 95;
  }
  return y;
}

export function generateCompassReport(
  report: CarrierVettingReport,
  carrierData: CompassCarrierData
): PDFDoc {
  const doc = new PDFDocument({ margin: 50, size: "LETTER" });

  // ── Page 1: Header & Summary ──
  addHeader(doc);
  addFooter(doc);

  let y = 90;

  // Carrier info block
  y += 5;
  doc.fontSize(13).fillColor(COLOR.navy).font("Helvetica-Bold");
  doc.text(`Carrier: ${carrierData.companyName.toUpperCase()}`, 50, y);
  y += 18;

  doc.fontSize(9).fillColor(COLOR.darkText).font("Helvetica");
  doc.text(`DOT#: ${carrierData.dotNumber}  |  MC#: ${carrierData.mcNumber}`, 50, y);
  y += 13;
  doc.text(`Contact: ${carrierData.contactName}  |  Tier: ${carrierData.tier}  |  Milestone: ${carrierData.milestone}`, 50, y);
  y += 13;
  doc.text(`Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 50, y);
  y += 20;

  drawSeparator(doc, y);
  y += 15;

  // ── Overall Assessment ──
  doc.fontSize(11).fillColor(COLOR.navy).font("Helvetica-Bold");
  doc.text("OVERALL ASSESSMENT", 50, y);
  y += 20;

  // Score box
  const scoreColor = report.score >= 80 ? COLOR.pass : report.score >= 60 ? COLOR.warning : COLOR.fail;
  doc.roundedRect(60, y, 120, 50, 4).fillAndStroke(scoreColor, scoreColor);
  doc.fontSize(22).fillColor("#ffffff").font("Helvetica-Bold");
  doc.text(`${report.score}/100`, 65, y + 8, { width: 110, align: "center" });
  doc.fontSize(8).fillColor("#ffffff").font("Helvetica");
  doc.text("SCORE", 65, y + 34, { width: 110, align: "center" });

  // Grade box
  doc.roundedRect(195, y, 70, 50, 4).fillAndStroke(COLOR.navy, COLOR.navy);
  doc.fontSize(22).fillColor(COLOR.gold).font("Helvetica-Bold");
  doc.text(report.grade, 195, y + 8, { width: 70, align: "center" });
  doc.fontSize(8).fillColor("#ffffff").font("Helvetica");
  doc.text("GRADE", 195, y + 34, { width: 70, align: "center" });

  // Risk & Recommendation
  doc.fontSize(10).fillColor(COLOR.darkText).font("Helvetica");
  doc.text(`Risk Level: ${report.riskLevel}`, 290, y + 8);
  doc.text(`Recommendation: ${report.recommendation}`, 290, y + 24);
  if (report.scoreDelta !== null) {
    const arrow = report.scoreDelta > 0 ? "+" : "";
    doc.text(`Trend: ${report.trendDirection || "N/A"} (${arrow}${report.scoreDelta})`, 290, y + 40);
  }

  y += 65;
  drawSeparator(doc, y);
  y += 15;

  // ── Detailed Check Results ──
  doc.fontSize(11).fillColor(COLOR.navy).font("Helvetica-Bold");
  doc.text(`DETAILED CHECK RESULTS (${report.checks.length} Checks)`, 50, y);
  y += 20;

  // Build a map for efficient lookup: assign each check its 1-based index
  const checkMap = new Map<number, VettingCheck>();
  report.checks.forEach((check, i) => {
    checkMap.set(i + 1, check);
  });

  // Track which checks we've already rendered to avoid duplicates across categories
  const rendered = new Set<number>();

  for (const category of CATEGORIES) {
    y = ensureSpace(doc, 30);

    doc.fontSize(9).fillColor(COLOR.gold).font("Helvetica-Bold");
    doc.text(`  ${category.name.toUpperCase()}`, 50, y);
    y += 14;

    for (const idx of category.indices) {
      if (rendered.has(idx)) continue;
      const check = checkMap.get(idx);
      if (!check) continue;
      rendered.add(idx);

      y = ensureSpace(doc, 14);

      const symbol = SYMBOL[check.result];
      const color = RESULT_COLOR[check.result];

      doc.fontSize(8).fillColor(color).font("Helvetica-Bold");
      doc.text(`  ${symbol}`, 60, y, { continued: true });
      doc.fillColor(COLOR.darkText).font("Helvetica");
      doc.text(` ${check.name}: `, { continued: true });
      doc.fillColor(color).font("Helvetica");
      doc.text(check.detail, { width: 440 });
      y = (doc as any).y + 3;
    }

    y += 6;
  }

  // Render any remaining checks not in defined categories
  report.checks.forEach((check, i) => {
    if (rendered.has(i + 1)) return;

    y = ensureSpace(doc, 14);
    const symbol = SYMBOL[check.result];
    const color = RESULT_COLOR[check.result];

    doc.fontSize(8).fillColor(color).font("Helvetica-Bold");
    doc.text(`  ${symbol}`, 60, y, { continued: true });
    doc.fillColor(COLOR.darkText).font("Helvetica");
    doc.text(` ${check.name}: `, { continued: true });
    doc.fillColor(color).font("Helvetica");
    doc.text(check.detail, { width: 440 });
    y = (doc as any).y + 3;
  });

  y += 10;

  // ── Flags & Warnings ──
  if (report.flags.length > 0) {
    y = ensureSpace(doc, 30 + report.flags.length * 14);
    drawSeparator(doc, y);
    y += 12;

    doc.fontSize(11).fillColor(COLOR.navy).font("Helvetica-Bold");
    doc.text("FLAGS & WARNINGS", 50, y);
    y += 18;

    for (const flag of report.flags) {
      y = ensureSpace(doc, 14);
      doc.fontSize(8).fillColor(COLOR.warning).font("Helvetica-Bold");
      doc.text(`  \u26A0`, 60, y, { continued: true });
      doc.fillColor(COLOR.darkText).font("Helvetica");
      doc.text(` ${flag}`, { width: 460 });
      y = (doc as any).y + 3;
    }
  }

  // Final separator
  y = ensureSpace(doc, 30);
  drawSeparator(doc, y);

  doc.end();
  return doc;
}
