import { Response } from "express";
import { prisma } from "../config/database";
import { AuthRequest } from "../middleware/auth";
import { createLoadWithTenderSchema } from "../validators/withTender";
import { complianceCheck } from "../services/complianceMonitorService";
import { notifyTenderAction } from "../services/notificationService";
import { autoGenerateRateConfirmation } from "../services/autoRateConfirmationService";
import { logLoadActivity } from "../services/loadActivityService";
import { checkCustomerActive } from "../lib/customerActive";
import { log } from "../lib/logger";

/**
 * Sprint 59 (v3.8.acj) Item 176 — POST /api/loads/with-tender
 *
 * Atomic Load + LoadTender + RateConfirmation creation for the Carrier
 * Engagement Drawer Mode 1 (build-and-tender). Replaces the broken
 * /api/orders/:id/convert-to-load → no createTender call chain
 * (Item 167 silent failure).
 *
 * Transaction shape:
 *   1. complianceCheck (outside tx — pure read)
 *   2. prisma.$transaction:
 *      a. Load.create (status="TENDERED", posterId=req.user.id)
 *      b. LoadTender.create (status="OFFERED", linked to load)
 *      c. autoGenerateRateConfirmation (DRAFT, autoGenerated=true)
 *      d. Order.update if orderId provided (status="load_created")
 *   3. Post-commit side effects (non-blocking try/catch):
 *      - notifyTenderAction("OFFERED") — email carrier + AE CC
 *      - sendTrackingLinkToCrmContacts — shipper contacts
 *      - logLoadActivity — activity feed entry
 *
 * Atomic guarantee: if any DB write fails, transaction rolls back. The
 * three rows commit together or not at all. Side effects are best-
 * effort and DO NOT trigger rollback (Sprint 38 Item 52 precedent).
 */
export async function createLoadWithTender(req: AuthRequest, res: Response) {
  let payload;
  try {
    payload = createLoadWithTenderSchema.parse(req.body);
  } catch (err: any) {
    res.status(400).json({
      error: "VALIDATION_ERROR",
      message: err?.errors?.[0]?.message ?? "Invalid request payload",
      details: err?.errors,
    });
    return;
  }

  const { tender, lineItems, orderId, ...loadFields } = payload;

  // Pre-flight: carrier exists + compliance gate (outside tx — pure reads)
  const carrier = await prisma.carrierProfile.findUnique({
    where: { id: tender.carrierId },
  });
  if (!carrier) {
    res.status(404).json({ error: "CARRIER_NOT_FOUND", message: "Carrier profile not found" });
    return;
  }

  const compliance = await complianceCheck(tender.carrierId);
  if (!compliance.allowed) {
    res.status(409).json({
      error: "CARRIER_INELIGIBLE",
      message: "Carrier is not eligible for tender",
      blocked_reasons: compliance.blocked_reasons,
    });
    return;
  }

  // v3.8.alr §13.3 Item 8.1 — block new loads against an inactive customer
  // (ADMIN/CEO override).
  const activeCheck = await checkCustomerActive(loadFields.customerId, req.user?.role);
  if (!activeCheck.allowed) {
    res.status(403).json({ error: "CUSTOMER_INACTIVE", message: activeCheck.reason });
    return;
  }

  // Order existence check if orderId provided (outside tx for clearer error)
  if (orderId) {
    const order = await prisma.order.findUnique({ where: { id: orderId } });
    if (!order) {
      res.status(404).json({ error: "ORDER_NOT_FOUND", message: "Draft order not found" });
      return;
    }
    if (order.loadId) {
      res.status(409).json({
        error: "ORDER_ALREADY_CONVERTED",
        message: "This draft has already been converted to a load",
        loadId: order.loadId,
      });
      return;
    }
  }

  // Generate reference numbers
  const refNumber = `L${Date.now().toString().slice(-8)}${Math.floor(Math.random() * 100)}`;
  const bolNumber = `BOL-${Date.now().toString().slice(-8)}`;
  const isHot = loadFields.shipmentPriority === "hot";

  try {
    const result = await prisma.$transaction(async (tx) => {
      // 1. Load.create — status=TENDERED directly (drawer flow skips
      //    transient POSTED state since we know the tender at creation).
      const load = await tx.load.create({
        data: {
          referenceNumber: refNumber,
          loadNumber: refNumber,
          bolNumber,
          customerId: loadFields.customerId,
          posterId: req.user!.id,

          // Lane
          originCity: loadFields.originCity,
          originState: loadFields.originState,
          originZip: loadFields.originZip,
          originAddress: loadFields.originAddress ?? null,
          originCompany: loadFields.originCompany ?? null,
          originContactName: loadFields.originContactName ?? null,
          originContactPhone: loadFields.originContactPhone ?? null,
          destCity: loadFields.destCity,
          destState: loadFields.destState,
          destZip: loadFields.destZip,
          destAddress: loadFields.destAddress ?? null,
          destCompany: loadFields.destCompany ?? null,
          destContactName: loadFields.destContactName ?? null,
          destContactPhone: loadFields.destContactPhone ?? null,
          distance: loadFields.distance ?? null,

          // Equipment & Freight
          equipmentType: loadFields.equipmentType,
          commodity: loadFields.commodity ?? null,
          weight: loadFields.weight ?? null,
          pieces: loadFields.pieces ?? null,
          hazmat: loadFields.hazmat,
          temperatureControlled: loadFields.temperatureControlled,
          tempMin: loadFields.tempMin ?? null,
          tempMax: loadFields.tempMax ?? null,

          // Schedule
          pickupDate: loadFields.pickupDate,
          pickupTimeStart: loadFields.pickupTimeStart ?? null,
          pickupTimeEnd: loadFields.pickupTimeEnd ?? null,
          deliveryDate: loadFields.deliveryDate,
          deliveryTimeStart: loadFields.deliveryTimeStart ?? null,
          deliveryTimeEnd: loadFields.deliveryTimeEnd ?? null,

          // Stops & References
          isMultiStop: loadFields.isMultiStop,
          stops: loadFields.stops ?? undefined,
          poNumbers: loadFields.poNumbers,
          appointmentNumber: loadFields.appointmentNumber ?? null,
          shipperReference: loadFields.shipperReference ?? null,
          deliveryReference: loadFields.deliveryReference ?? null,

          // Financials — fuelSurcharge dropped from drawer scope at
          // Sprint 59.b per Item 176; RC generation hardcodes 0 and AE
          // adjusts on the RC PDF surface post-acceptance.
          rate: tender.offeredRate,
          customerRate: loadFields.customerRate ?? null,
          carrierRate: tender.offeredRate,
          accessorials: loadFields.accessorials ?? undefined,

          // Instructions
          specialInstructions: loadFields.specialInstructions ?? null,
          pickupInstructions: loadFields.pickupInstructions ?? null,
          deliveryInstructions: loadFields.deliveryInstructions ?? null,

          // Dispatch — drawer is always direct_tender
          dispatchMethod: "direct_tender",
          visibility: "reserved",
          shipmentPriority: loadFields.shipmentPriority,
          isHotLoad: isHot,
          urgencyLevel: isHot ? "EXPEDITED" : "STANDARD",
          checkCallProtocol: loadFields.checkCallProtocol,
          trackingLinkAutoSend: loadFields.trackingLinkAutoSend,

          // Status — TENDERED on creation since the tender is part of the
          // same atomic write (skips POSTED transient state).
          status: "TENDERED",
          tenderedAt: new Date(),
          tenderedById: req.user!.id,

          // Line items (nested create)
          lineItems: {
            create: lineItems.map((li) => ({
              lineNumber: li.lineNumber,
              pieces: li.pieces,
              packageType: li.packageType ?? "PLT",
              description: li.description,
              weight: li.weight,
              dimensionsLength: li.dimensionsLength ?? null,
              dimensionsWidth: li.dimensionsWidth ?? null,
              dimensionsHeight: li.dimensionsHeight ?? null,
              freightClass: li.freightClass ?? null,
              nmfcCode: li.nmfcCode ?? null,
              hazmat: li.hazmat,
              hazmatUnNumber: li.hazmatUnNumber ?? null,
              hazmatClass: li.hazmatClass ?? null,
              hazmatEmergencyContact: li.hazmatEmergencyContact ?? null,
              hazmatPlacardRequired: li.hazmatPlacardRequired ?? null,
              stackable: li.stackable ?? true,
              turnable: li.turnable ?? true,
            })),
          },
        } as any,
      });

      // 2. LoadTender.create
      const loadTender = await tx.loadTender.create({
        data: {
          loadId: load.id,
          carrierId: tender.carrierId,
          offeredRate: tender.offeredRate,
          expiresAt: tender.expiresAt,
        },
      });

      // 3. autoGenerateRateConfirmation — passes tx for transaction enrollment
      //    on the RC.create write per Sprint 59 Risk 4 resolution.
      const rc = await autoGenerateRateConfirmation(
        load.id,
        loadTender.id,
        req.user!.id,
        tx as any,
      );

      // 4. Order.update if orderId provided (drawer launched from Order
      //    Builder draft). Marks the draft as converted with loadId
      //    backreference for audit trail.
      if (orderId) {
        await tx.order.update({
          where: { id: orderId },
          data: { status: "load_created", loadId: load.id },
        });
      }

      return { load, tender: loadTender, rc };
    });

    // Post-commit side effects — non-blocking try/catch per Sprint 38 pattern.
    // Email failures must NOT roll back the load/tender/RC.
    notifyTenderAction(result.tender.id, "OFFERED").catch((err) =>
      log.error({ err, tenderId: result.tender.id }, "[with-tender] notifyTenderAction failed"),
    );

    if (loadFields.trackingLinkAutoSend !== false) {
      import("../services/shipperLoadNotifyService")
        .then(({ sendTrackingLinkToCrmContacts }) => sendTrackingLinkToCrmContacts(result.load.id))
        .catch((err) => log.error({ err, loadId: result.load.id }, "[with-tender] tracking link fan-out failed"));
    }

    logLoadActivity({
      loadId: result.load.id,
      eventType: "load_created",
      description: `Load created via Carrier Engagement Drawer · tendered to carrier ${tender.carrierId} at $${tender.offeredRate.toLocaleString()}`,
      actorType: "USER",
      actorId: req.user!.id,
      actorName: req.user!.email,
      metadata: {
        tenderId: result.tender.id,
        rcId: result.rc?.id,
        orderId: orderId ?? null,
        sprint: "59",
      },
    }).catch((err) => log.error({ err }, "[with-tender] activity log failed"));

    res.status(201).json({
      load: result.load,
      tender: result.tender,
      rateConfirmation: result.rc,
    });
  } catch (err: any) {
    log.error({ err }, "[with-tender] transaction rollback");
    res.status(500).json({
      error: "TRANSACTION_FAILED",
      message: "Failed to create load with tender. No changes were persisted.",
    });
  }
}
