import { Router } from "express";
import authRoutes from "./auth";
import loadRoutes from "./loads";
import invoiceRoutes from "./invoices";
import documentRoutes from "./documents";
import carrierRoutes from "./carrier";
import tenderRoutes from "./tenders";
import messageRoutes from "./messages";
import notificationRoutes from "./notifications";
import integrationRoutes from "./integrations";
import shipmentRoutes from "./shipments";
import customerRoutes from "./customers";
import driverRoutes from "./drivers";
import equipmentRoutes from "./equipment";
import sopRoutes from "./sops";
import accountingRoutes from "./accounting";
import pdfRoutes from "./pdf";
import marketRoutes from "./market";
import ediRoutes from "./edi";
import fleetRoutes from "./fleet";
import complianceRoutes from "./compliance";
import auditRoutes from "./audit";

const router = Router();

router.use("/auth", authRoutes);
router.use("/loads", loadRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/documents", documentRoutes);
router.use("/carrier", carrierRoutes);
router.use("/", tenderRoutes);
router.use("/messages", messageRoutes);
router.use("/notifications", notificationRoutes);
router.use("/integrations", integrationRoutes);
router.use("/shipments", shipmentRoutes);
router.use("/customers", customerRoutes);
router.use("/drivers", driverRoutes);
router.use("/equipment", equipmentRoutes);
router.use("/sops", sopRoutes);
router.use("/accounting", accountingRoutes);
router.use("/pdf", pdfRoutes);
router.use("/market", marketRoutes);
router.use("/edi", ediRoutes);
router.use("/fleet", fleetRoutes);
router.use("/compliance", complianceRoutes);
router.use("/audit", auditRoutes);

export default router;
