-- RECONCILE step 2 (2026-09-26): an invoice records how it reached the customer.
--
-- WHY. Four Beekeepers invoices were delivered by upload to the customer's Tipalti
-- AP portal. The schema could only say SENT, and SENT was read everywhere as "we
-- emailed it". This adds the channel, when the customer received it, and who
-- recorded it, plus a per-customer default channel.
--
-- AMENDED (item 3, 2026-09-26) before it reached any shared database: the
-- delivered file. deliveredFileHash is the SHA-256 of the exact bytes the
-- customer received, and archivedDocumentId links the stored copy of those
-- bytes. UNIQUE, so one stored file is the archive of one invoice. RESTRICT,
-- so the archive cannot be deleted while an invoice names it.
--
-- ADDITIVE. One enum; five nullable invoice columns; one NOT NULL customer
-- column with a default, so every existing customer reads EMAIL, which is how
-- each is billed today; one unique index; one foreign key. No backfill: a
-- channel is recorded when a document leaves SRL, and inventing one for an
-- invoice sent before this existed would put a confident value on a guess.
--
-- RELEASE. Approved for production 2026-09-26 once amended, applied through the
-- guarded rail ahead of the code (schema-ahead-of-code, §13.3 Item 213).
--
-- SQL generated by `prisma migrate diff` between the two datamodels, not typed.

-- CreateEnum
CREATE TYPE "InvoiceDeliveryChannel" AS ENUM ('EMAIL', 'TIPALTI', 'MANUAL');

-- AlterTable
ALTER TABLE "invoices" ADD COLUMN     "archivedDocumentId" TEXT,
ADD COLUMN     "deliveredAt" TIMESTAMP(3),
ADD COLUMN     "deliveredById" TEXT,
ADD COLUMN     "deliveredFileHash" TEXT,
ADD COLUMN     "deliveryChannel" "InvoiceDeliveryChannel";

-- AlterTable
ALTER TABLE "customers" ADD COLUMN     "defaultInvoiceChannel" "InvoiceDeliveryChannel" NOT NULL DEFAULT 'EMAIL';

-- CreateIndex
CREATE UNIQUE INDEX "invoices_archivedDocumentId_key" ON "invoices"("archivedDocumentId");

-- AddForeignKey
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_archivedDocumentId_fkey" FOREIGN KEY ("archivedDocumentId") REFERENCES "documents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
