-- RECONCILE step 2 (2026-09-26): an invoice records how it reached the customer.
--
-- WHY. Four Beekeepers invoices were delivered by upload to the customer's Tipalti
-- AP portal. The schema could only say SENT, and SENT was read everywhere as "we
-- emailed it". This adds the channel, when the customer received it, and who
-- recorded it, plus a per-customer default channel.
--
-- ADDITIVE. One enum; three nullable invoice columns; one NOT NULL customer column
-- with a default, so every existing customer reads EMAIL, which is how each is
-- billed today. No backfill: a channel is recorded when a document leaves SRL,
-- and inventing one for an invoice sent before this existed would put a
-- confident value on a guess.
--
-- HELD. Authored on hold/invoice-delivery-channel. Applying it to production is
-- an open decision; merging the branch is the release act (CLAUDE.md §2.2).
--
-- SQL generated by `prisma migrate diff` between the two datamodels, not typed.

-- CreateEnum
CREATE TYPE "InvoiceDeliveryChannel" AS ENUM ('EMAIL', 'TIPALTI', 'MANUAL');

-- AlterTable
ALTER TABLE "invoices" ADD COLUMN     "deliveredAt" TIMESTAMP(3),
ADD COLUMN     "deliveredById" TEXT,
ADD COLUMN     "deliveryChannel" "InvoiceDeliveryChannel";

-- AlterTable
ALTER TABLE "customers" ADD COLUMN     "defaultInvoiceChannel" "InvoiceDeliveryChannel" NOT NULL DEFAULT 'EMAIL';
