-- Carrier-archive arc B1 (2026-09-19). Additive: one enum, two nullable columns on
-- carrier_profiles. No backfill, no drop. Generated by `prisma migrate diff
-- --from-schema-datamodel <HEAD> --to-schema-datamodel <B1>`; never applied from a
-- local shell — Render's build chain applies it when this commit deploys (§2.2).

-- CreateEnum
CREATE TYPE "CarrierArchiveReason" AS ENUM ('DUPLICATE_RECORD', 'CEASED_OPERATIONS', 'AUTHORITY_REVOKED', 'FRAUD_CONFIRMED', 'INSURANCE_LAPSED_UNRESPONSIVE', 'RELATIONSHIP_ENDED', 'ERRONEOUS_RECORD');
-- AlterTable
ALTER TABLE "carrier_profiles" ADD COLUMN     "archiveNote" TEXT,
ADD COLUMN     "archiveReason" "CarrierArchiveReason";
