-- Sprint Phase 2 (v3.8.acd) — autoGenerated flag on RateConfirmation.
-- Distinguishes RCs created by autoRateConfirmationService on tender
-- accept (the new automated path) from RCs created by AE staff via the
-- existing POST /api/rate-confirmations/ manual flow.
--
-- Additive: existing RC rows default to false, preserving prior semantics.
-- AE Console review surface reads this column to mark auto-drafts visibly.

ALTER TABLE "public"."rate_confirmations" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
