-- Extend UserRole enum with new roles
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DISPATCH';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'OPERATIONS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ACCOUNTING';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CEO';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'READONLY';

-- Extend LoadStatus enum with new statuses
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'PLANNED';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'TENDERED';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'DISPATCHED';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'AT_PICKUP';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'LOADED';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'AT_DELIVERY';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'POD_RECEIVED';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'INVOICED';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'TONU';
ALTER TYPE "LoadStatus" ADD VALUE IF NOT EXISTS 'PICKED_UP';

-- Extend InvoiceStatus enum with new statuses
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'SENT';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'PARTIAL';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'OVERDUE';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'VOID';
